// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Veripark.PenaltyCalculation.MvcUI.Models
{

    // Country
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class Country
    {
        public int Id { get; set; } // Id (Primary key)
        public string Name { get; set; } // Name (length: 300)

        // Reverse navigation

        /// <summary>
        /// Child Currencies where [Currency].[CountryId] point to this entity (FK_Currency_Country)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Currency> Currencies { get; set; } // Currency.FK_Currency_Country
        /// <summary>
        /// Child Holidays where [Holiday].[CountryId] point to this entity (FK_Holiday_Country)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Holiday> Holidays { get; set; } // Holiday.FK_Holiday_Country
        /// <summary>
        /// Child Penalizes where [Penalize].[CountryId] point to this entity (FK_Penalize_Country)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Penalize> Penalizes { get; set; } // Penalize.FK_Penalize_Country
        /// <summary>
        /// Child Weekends where [Weekend].[CountryId] point to this entity (FK_Weekend_Country)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Weekend> Weekends { get; set; } // Weekend.FK_Weekend_Country

        public Country()
        {
            Currencies = new System.Collections.Generic.List<Currency>();
            Holidays = new System.Collections.Generic.List<Holiday>();
            Penalizes = new System.Collections.Generic.List<Penalize>();
            Weekends = new System.Collections.Generic.List<Weekend>();
        }
    }

}
// </auto-generated>
