// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Veripark.PenaltyCalculation.MvcUI.Models
{

    // Holiday
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class Holiday
    {
        public int Id { get; set; } // Id (Primary key)
        public int CountryId { get; set; } // CountryId
        public string Name { get; set; } // Name (length: 300)
        public System.DateTime Date { get; set; } // Date

        // Foreign keys

        /// <summary>
        /// Parent Country pointed by [Holiday].([CountryId]) (FK_Holiday_Country)
        /// </summary>
        public virtual Country Country { get; set; } // FK_Holiday_Country
    }

}
// </auto-generated>
