// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Veripark.PenaltyCalculation.MvcUI.Models
{

    // Holiday
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class HolidayConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Holiday>
    {
        public HolidayConfiguration()
            : this("dbo")
        {
        }

        public HolidayConfiguration(string schema)
        {
            ToTable("Holiday", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.CountryId).HasColumnName(@"CountryId").HasColumnType("int").IsRequired();
            Property(x => x.Name).HasColumnName(@"Name").HasColumnType("nvarchar").IsRequired().HasMaxLength(300);
            Property(x => x.Date).HasColumnName(@"Date").HasColumnType("datetime").IsRequired();

            // Foreign keys
            HasRequired(a => a.Country).WithMany(b => b.Holidays).HasForeignKey(c => c.CountryId).WillCascadeOnDelete(false); // FK_Holiday_Country
        }
    }

}
// </auto-generated>
