// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Veripark.PenaltyCalculation.MvcUI.Models
{


    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class PenaltyCalculationDbContext : System.Data.Entity.DbContext, IPenaltyCalculationDbContext
    {
        public System.Data.Entity.DbSet<Country> Countries { get; set; } // Country
        public System.Data.Entity.DbSet<Currency> Currencies { get; set; } // Currency
        public System.Data.Entity.DbSet<Holiday> Holidays { get; set; } // Holiday
        public System.Data.Entity.DbSet<Penalize> Penalizes { get; set; } // Penalize
        public System.Data.Entity.DbSet<Weekend> Weekends { get; set; } // Weekend

        static PenaltyCalculationDbContext()
        {
            System.Data.Entity.Database.SetInitializer<PenaltyCalculationDbContext>(null);
        }

        public PenaltyCalculationDbContext()
            : base("Name=PenaltyCalculationConn")
        {
        }

        public PenaltyCalculationDbContext(string connectionString)
            : base(connectionString)
        {
        }

        public PenaltyCalculationDbContext(string connectionString, System.Data.Entity.Infrastructure.DbCompiledModel model)
            : base(connectionString, model)
        {
        }

        public PenaltyCalculationDbContext(System.Data.Common.DbConnection existingConnection, bool contextOwnsConnection)
            : base(existingConnection, contextOwnsConnection)
        {
        }

        public PenaltyCalculationDbContext(System.Data.Common.DbConnection existingConnection, System.Data.Entity.Infrastructure.DbCompiledModel model, bool contextOwnsConnection)
            : base(existingConnection, model, contextOwnsConnection)
        {
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
        }

        public bool IsSqlParameterNull(System.Data.SqlClient.SqlParameter param)
        {
            var sqlValue = param.SqlValue;
            var nullableValue = sqlValue as System.Data.SqlTypes.INullable;
            if (nullableValue != null)
                return nullableValue.IsNull;
            return (sqlValue == null || sqlValue == System.DBNull.Value);
        }

        protected override void OnModelCreating(System.Data.Entity.DbModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            modelBuilder.Configurations.Add(new CountryConfiguration());
            modelBuilder.Configurations.Add(new CurrencyConfiguration());
            modelBuilder.Configurations.Add(new HolidayConfiguration());
            modelBuilder.Configurations.Add(new PenalizeConfiguration());
            modelBuilder.Configurations.Add(new WeekendConfiguration());
        }

        public static System.Data.Entity.DbModelBuilder CreateModel(System.Data.Entity.DbModelBuilder modelBuilder, string schema)
        {
            modelBuilder.Configurations.Add(new CountryConfiguration(schema));
            modelBuilder.Configurations.Add(new CurrencyConfiguration(schema));
            modelBuilder.Configurations.Add(new HolidayConfiguration(schema));
            modelBuilder.Configurations.Add(new PenalizeConfiguration(schema));
            modelBuilder.Configurations.Add(new WeekendConfiguration(schema));
            return modelBuilder;
        }
    }
}
// </auto-generated>
