// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Veripark.PenaltyCalculation.MvcUI.Models
{

    public class PenaltyCalculationDbContextFactory : System.Data.Entity.Infrastructure.IDbContextFactory<PenaltyCalculationDbContext>
    {
        public PenaltyCalculationDbContext Create()
        {
            return new PenaltyCalculationDbContext();
        }
    }
}
// </auto-generated>
