// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Veripark.PenaltyCalculation.MvcUI.Models
{

    // Weekend
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class WeekendConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Weekend>
    {
        public WeekendConfiguration()
            : this("dbo")
        {
        }

        public WeekendConfiguration(string schema)
        {
            ToTable("Weekend", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.DayOfWeek).HasColumnName(@"DayOfWeek").HasColumnType("nvarchar").IsRequired().HasMaxLength(300);
            Property(x => x.CountryId).HasColumnName(@"CountryId").HasColumnType("int").IsRequired();

            // Foreign keys
            HasRequired(a => a.Country).WithMany(b => b.Weekends).HasForeignKey(c => c.CountryId).WillCascadeOnDelete(false); // FK_Weekend_Country
        }
    }

}
// </auto-generated>
