// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Veripark.PenaltyCalculation.MvcUI.Models
{

    // Weekend
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class Weekend
    {
        public int Id { get; set; } // Id (Primary key)
        public string DayOfWeek { get; set; } // DayOfWeek (length: 300)
        public int CountryId { get; set; } // CountryId

        // Foreign keys

        /// <summary>
        /// Parent Country pointed by [Weekend].([CountryId]) (FK_Weekend_Country)
        /// </summary>
        public virtual Country Country { get; set; } // FK_Weekend_Country
    }

}
// </auto-generated>
